name: 'unit'

on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'

    - uses: 'actions/setup-go@v2'
      with:
        go-version: '1.17'

    - run: go test -count=1 -race -timeout=5m -shuffle=on -vet=all ./...
